<a href="https://colab.research.google.com/github/sourav297/AI_tetsing_projects/blob/main/Decesion_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#load files
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic.csv


In [ ]:
#read the csv file
df = pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

Here use only 'Survived', 'Pclass', 'Sex', 'Age', 'Fare' columns to build the model and 'Survived' is the target feature.

1.   List item
2.   List item



In [ ]:
df = df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'], axis=1)
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [ ]:
inputs.head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [ ]:
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_Sex = LabelEncoder()

In [ ]:
inputs['Sex_n'] = le_Sex.fit_transform(inputs['Sex'])
inputs.head()

Pclass     Sex   Age     Fare  Sex_n
0       3    male  22.0   7.2500      1
1       1  female  38.0  71.2833      0
2       3  female  26.0   7.9250      0
3       1  female  35.0  53.1000      0
4       3    male  35.0   8.0500      1

In [ ]:
new_inputs = inputs.drop(['Sex'], axis='columns')
new_inputs.head()

Pclass   Age     Fare  Sex_n
0       3  22.0   7.2500      1
1       1  38.0  71.2833      0
2       3  26.0   7.9250      0
3       1  35.0  53.1000      0
4       3  35.0   8.0500      1

In [ ]:
new_inputs.columns[new_inputs.isna().any()]

Index(['Age'], dtype='object')

In [ ]:
new_inputs.Age = new_inputs.Age.fillna(new_inputs.Age.mean())
new_inputs.head()

Pclass   Age     Fare  Sex_n
0       3  22.0   7.2500      1
1       1  38.0  71.2833      0
2       3  26.0   7.9250      0
3       1  35.0  53.1000      0
4       3  35.0   8.0500      1

In [ ]:
new_inputs.columns[new_inputs.isna().any()]

Index([], dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(new_inputs,target,test_size=0.2, random_state=17)

In [ ]:
X_train.head()

Pclass        Age     Fare  Sex_n
873       3  47.000000   9.0000      1
828       3  29.699118   7.7500      1
99        2  34.000000  26.0000      1
523       1  44.000000  57.9792      0
132       3  47.000000  14.5000      0

In [ ]:
y_train.head()

873    0
828    1
99     0
523    1
132    0
Name: Survived, dtype: int64

In [ ]:
X_train.shape

(712, 4)

In [ ]:
X_test.shape

(179, 4)

In [ ]:
#import the decision tree class and create a object of this class and then train the model
from sklearn import tree
my_model = tree.DecisionTreeClassifier()

In [ ]:
my_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
my_model.score(X_test, y_test)

0.8044692737430168

In [ ]:
my_model.predict([[1, 44.000000, 57.9792, 0]])  # 523 th row of X_train

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [ ]:
my_model.predict([[3, 47.000000, 14.5000, 0]])  # 132 th row of X_train

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])





**Save Model to a file using python pickle**

In [ ]:
import pickle

In [ ]:
# save the model
with open ('model_pickle', 'wb') as file:
  pickle.dump(my_model, file)

In [ ]:
#Load saved model
with open ('model_pickle', 'rb') as file:
  mp = pickle.load(file)

In [ ]:
mp.predict([[1, 44.000000, 57.9792, 0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])