<a href="https://colab.research.google.com/github/sourav297/AI_tetsing_projects/blob/main/Linear_Regression_Multi_Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

For multiple variable the Linear Regression model will be like
`y = m1*x1 + m2*x2 + m3*x3 + ... + mn*xn + c`
where m1, m2,..., mn are coefficients and x1, x2, ..., xn are input features

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
#resd the 'homeprices.csv' file
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

There is a empty value in bedrooms column, So we have to first preprocess the data and for that I use here median to fill the empty or NaN field

In [ ]:
df.bedrooms.median()

4.0

In [ ]:
#Now fill this value to the empty fields in the dataset by fillna() method
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
#Split the dataset into input and output datas
new_df = df.drop('price', axis = 'columns')
new_df.head()

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8

In [ ]:
price = df.price
price.head()

0    550000
1    565000
2    610000
3    595000
4    760000
Name: price, dtype: int64

In [ ]:
#Now create a Linear Regression object and train the model
model = linear_model.LinearRegression()
#model.fit([['area', 'bedrooms', 'age']], df.price)  //This syntax can also be used
model.fit(new_df, price)

LinearRegression()

In [ ]:
#now print all the solpes or coefficients
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
#now print the intercept
model.intercept_

221323.00186540396

In [ ]:
#now predict the price of a home with area = 3000, bedrooms = 3, age = 40
model.predict([[3000, 3, 40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [ ]:
#validation of the prediction
# y = m1*x1 + m2*x2 + m3*x3 + c
y = 112.06244194*3000 + 23388.88007794*3 + (-3231.71790863*40) + 221323.00186540396
print(y)

498408.251574024


In [ ]:
#now predict the price of a home with area = 2500, bedrooms = 4, age = 5
model.predict([[2500, 4, 5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [ ]:
#now predict the price of a home with area = 4100, bedrooms = 6, age = 2
model.predict([[4100, 6, 2]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([814648.85847853])

Now build a Linear Regression model to predict the salary based on the 3 independent variable or input feature experience, test_score(out of 10) and interview_score(out of 10)...
First download the 'hiring.csv' file and then do rest of the work.

In [ ]:
dataset = pd.read_csv('hiring.csv')
dataset

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

Now preprocess the dataset

In [ ]:
#rename the 2nd and 3rd ans 4th column
dataset.rename(columns = {'test_score(out of 10)': 'test_score', 'interview_score(out of 10)' : 'interview_score', 'salary($)' : 'salary'}, inplace = True)
dataset

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [ ]:
#fill the empty cell in test_score column by the mean of that column
import math
test_mean = math.floor(dataset.test_score.mean())
print(test_mean)
dataset.test_score = dataset.test_score.fillna(test_mean)
dataset.experience = dataset.experience.fillna('zero')
dataset

7


experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [ ]:
#convert the values in experience column to numeric value
!pip install word2number
from word2number import w2n

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=083689c17b25302b6a00b18778298d31e8fecdd0692e6a49c73b56f89eefc86c
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [ ]:
#Now we can use the module word2number
dataset.experience = dataset.experience.astype(str).apply(w2n.word_to_num)
dataset

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [ ]:
#now split the dataset into input and output datas
#This is input part
new_dataset = dataset.drop('salary', axis = 'columns')
new_dataset

experience  test_score  interview_score
0           0         8.0                9
1           0         8.0                6
2           5         6.0                7
3           2        10.0               10
4           7         9.0                6
5           3         7.0               10
6          10         8.0                7
7          11         7.0                8

In [ ]:
#This is output part
salary = dataset.salary
salary

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [ ]:
#now create the object for Linear Regression and train the model
hiring_model = linear_model.LinearRegression()
hiring_model.fit(new_dataset, salary)

LinearRegression()

In [ ]:
#print the slopes or coefficients
hiring_model.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [ ]:
#print the intercept
hiring_model.intercept_

17737.263464337688

In [ ]:
#predict for the new input features
hiring_model.predict([[2, 9, 6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [ ]:
hiring_model.predict([[12, 10, 10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])